### ISSUE TITLE
can't install

### ISSUE THREAD

**Issue by Akshay-Arjun** [kosmosec/proto-find#2]
![Screenshot 2022-03-08 190633](https://user-images.githubusercontent.com/68991993/157248656-7064a72e-7a29-43cc-bd00-434b10fa0e6a.png)

**Comment by kosmosec** [comment]
Could you check if you have the path for Go binaries (where the `go install` will place the binary) in your PATH? 
For example: the `go install` will place the Go binary in /home/<your name>/go/bin. You have to add this path to your env PATH variable.
