### ISSUE TITLE
unable to run tool

### ISSUE THREAD

**Issue by superdeen** [kosmosec/proto-find#3]
the tool returns this error after running;  proto-find -u ./urls -p ./payloads.txt -js window.elo

panic: close of closed channel

goroutine 35 [running]:
github.com/chromedp/chromedp.(*ExecAllocator).Allocate.func2()
        /home/coolcat/go/pkg/mod/github.com/chromedp/chromedp@v0.7.1/allocate.go:213 +0xc5
created by github.com/chromedp/chromedp.(*ExecAllocator).Allocate
        /home/coolcat/go/pkg/mod/github.com/chromedp/chromedp@v0.7.1/allocate.go:199 +0xcfd

**Comment by kosmosec** [comment]
Could you check if you have installed chromedp and google chrome in the latest version?
Please, share the version of the chromedp and google chrome for better context to understand the issue.

**Comment by superdeen** [comment]
Thanks for responding,

The latest version was installed.
In fact, another related tool as this worked quite well on my machine...

**Comment by kosmosec** [comment]
The problem is with the dependencies between chromedp and chrome. It should work now for Version 110.0.5481.177 (Official Build) (64-bit).
